// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFzi-XzCa829lyHz-Du-x_UN7eylu4-bI',
    appId: '1:520031501923:web:edfb7d03f251c7f012c256',
    messagingSenderId: '520031501923',
    projectId: 'fuel-and-fix-assist',
    authDomain: 'fuel-and-fix-assist.firebaseapp.com',
    storageBucket: 'fuel-and-fix-assist.firebasestorage.app',
    measurementId: 'G-03CVN12500',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuGxZdEFSN-5t4xgXUslO6zgTAOC3vWLA',
    appId: '1:520031501923:android:4424dbb198bf633312c256',
    messagingSenderId: '520031501923',
    projectId: 'fuel-and-fix-assist',
    storageBucket: 'fuel-and-fix-assist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB67vQ2wRRwD31QRZtw5DisqT24sk8VSqo',
    appId: '1:520031501923:ios:571de61a8e0326d312c256',
    messagingSenderId: '520031501923',
    projectId: 'fuel-and-fix-assist',
    storageBucket: 'fuel-and-fix-assist.firebasestorage.app',
    iosBundleId: 'com.example.fuelAndFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB67vQ2wRRwD31QRZtw5DisqT24sk8VSqo',
    appId: '1:520031501923:ios:571de61a8e0326d312c256',
    messagingSenderId: '520031501923',
    projectId: 'fuel-and-fix-assist',
    storageBucket: 'fuel-and-fix-assist.firebasestorage.app',
    iosBundleId: 'com.example.fuelAndFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFzi-XzCa829lyHz-Du-x_UN7eylu4-bI',
    appId: '1:520031501923:web:a398f52d91b626ba12c256',
    messagingSenderId: '520031501923',
    projectId: 'fuel-and-fix-assist',
    authDomain: 'fuel-and-fix-assist.firebaseapp.com',
    storageBucket: 'fuel-and-fix-assist.firebasestorage.app',
    measurementId: 'G-83JPFMXJJX',
  );
}
